### ISSUE TITLE
Peer-to-peer Code Review

### ISSUE THREAD

**Issue by fredericomba** [firmoholanda/spotify.com-clone#1]
The code is good overall. There are only very small issues. 
- The copyright information should be wrapped in a ```small``` element.
- Empty link might reload the page, so the ```href``` attribute should have a "#" (hashtag).
- Some images lack an "alt" attribute with content.
- Having one or two screenshots might help the presentation of the project.
- Maybe the CSS should be inside the 'assets' folder.
- Maybe adding some color and borders to the framework.
- There are two meaningless class that the only difference between them is the background color.

**Comment by firmoholanda** [comment]
thanks for the suggestions!
